<h1><?= $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?= $this->urlAdd;?>">Novo setor</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Código</th>
            <th>Nome</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?=$this->partialLoop('tropa/setor/setores.phtml', $this->paginator);?>
    </tbody>
</table>
<p><?=$this->paginationControl($this->paginator,'Sliding','pagination', array('route' => 'setor'));?></p>
<p><a href="<?=$this->urlHomepage;?>">Homepage</a></p>