<?php
$title = 'Setores';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?= $this->url('setor', array('action' => 'add')); ?>">Novo setor</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Código</th>
            <th>Nome</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->setores as $setor): ?>
        <tr>
            <td><?=$setor->codigo;?></td>
            <td><?=$this->escapeHtml($setor->nome);?></td>
            <td>
                <a href="<?=$this->url('setor', array('action' => 'edit', 'codigo' => $setor->codigo));?>">Editar</a>
                <a href="<?=$this->url('setor', array('action' => 'delete', 'codigo' => $setor->codigo));?>">Remover</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>