<?php
$title = 'Lanternas verdes';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?= $this->url('lanterna', array('action' => 'add')) ?>">Novo Lanterna</a>
</p>

<table class="table">
    <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Setor</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->lanternas as $lanterna): ?>
    <tr>
        <td><?=$this->escapeHtml($lanterna->codigo);?></td>
        <td><?=$this->escapeHtml($lanterna->nome);?></td>
        <td><?=$this->escapeHtml($lanterna->setor->nome);?></td>
        <td>
            <a href="<?=$this->url('lanterna', array('action' => 'edit', 'codigo' => $lanterna->codigo));?>">Editar</a>
            <a href="<?=$this->url('lanterna', array('action' => 'delete', 'codigo' => $lanterna->codigo));?>">Remover</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>