<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <?php echo $this->headTitle() ?>
        <meta charset="utf-8">
    </head>
    <body>
        <div class="container">
            <header>
                <p>Sistema de Controle de Tropa dos Lanternas Verdes</p>
            </header>
            <?php echo $this->content;?>
            <hr>
            <footer>
                <p>
                    &copy; 2014 by Oa. <?php echo $this->translate('All Right reserved.');?>
                </p>
            </footer>
        </div>
    </body>
</html>
